# Generated by Django 3.2.9 on 2021-12-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211221_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(default='kot', max_length=50),
        ),
    ]
