# Generated by Django 4.0 on 2021-12-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='percentages',
            field=models.CharField(default='', max_length=200),
        ),
    ]
